export interface Reaction {
    id:             string;
    reactionType:   string;
    reagents:       string[];
    tempC:          number;
    timeH:          number;
    solvent:        string;
    modulator:      string | null;
    yieldPct:       number;
    crystallinity:  'High' | 'Medium' | 'Low';
}

export const reactions: Reaction[] = [
    {
        id:            'RXN-001',
        reactionType:  'Solvothermal',
        reagents:      ['Zinc nitrate', 'Terephthalic acid', 'Triethylamine'],
        tempC:         120,
        timeH:         24,
        solvent:       'DMF',
        modulator:     'Acetic acid',
        yieldPct:      78,
        crystallinity: 'High',
    },
    {
        id:            'RXN-002',
        reactionType:  'Solvothermal',
        reagents:      ['Copper(II) acetate', 'Trimesic acid'],
        tempC:         150,
        timeH:         48,
        solvent:       'DMF',
        modulator:     null,
        yieldPct:      65,
        crystallinity: 'Medium',
    },
    {
        id:            'RXN-003',
        reactionType:  'Hydrothermal',
        reagents:      ['Aluminum sulfate', 'Terephthalic acid', 'NaOH'],
        tempC:         220,
        timeH:         72,
        solvent:       'Water',
        modulator:     null,
        yieldPct:      55,
        crystallinity: 'High',
    },
    {
        id:            'RXN-004',
        reactionType:  'Mechanochemical',
        reagents:      ['Zinc oxide', '2-Methylimidazole'],
        tempC:         25,
        timeH:         0.5,
        solvent:       'None',
        modulator:     null,
        yieldPct:      90,
        crystallinity: 'Low',
    },
    {
        id:            'RXN-005',
        reactionType:  'Microwave-Assisted',
        reagents:      ['Copper(II) nitrate', 'Trimesic acid', 'Triethylamine'],
        tempC:         140,
        timeH:         1,
        solvent:       'DMF',
        modulator:     'HCl',
        yieldPct:      72,
        crystallinity: 'Medium',
    },
    {
        id:            'RXN-006',
        reactionType:  'Solvothermal',
        reagents:      ['Iron(III) chloride', 'Terephthalic acid'],
        tempC:         150,
        timeH:         72,
        solvent:       'DMF',
        modulator:     'HF',
        yieldPct:      60,
        crystallinity: 'High',
    },
    {
        id:            'RXN-007',
        reactionType:  'Hydrothermal',
        reagents:      ['Nickel(II) chloride', 'DABCO', 'Terephthalic acid'],
        tempC:         180,
        timeH:         48,
        solvent:       'Water',
        modulator:     null,
        yieldPct:      48,
        crystallinity: 'Medium',
    },
    {
        id:            'RXN-008',
        reactionType:  'Reflux',
        reagents:      ['Cobalt(II) nitrate', 'Trimesic acid', 'Triethylamine'],
        tempC:         100,
        timeH:         12,
        solvent:       'Ethanol',
        modulator:     null,
        yieldPct:      42,
        crystallinity: 'Low',
    },
    {
        id:            'RXN-009',
        reactionType:  'Solvothermal',
        reagents:      ['Zirconium chloride', 'Terephthalic acid', 'Acetic acid'],
        tempC:         120,
        timeH:         24,
        solvent:       'DMF',
        modulator:     'Acetic acid',
        yieldPct:      85,
        crystallinity: 'High',
    },
    {
        id:            'RXN-010',
        reactionType:  'Solvothermal',
        reagents:      ['Zinc nitrate', '2-Methylimidazole'],
        tempC:         85,
        timeH:         24,
        solvent:       'Methanol',
        modulator:     null,
        yieldPct:      88,
        crystallinity: 'High',
    },
    {
        id:            'RXN-011',
        reactionType:  'Microwave-Assisted',
        reagents:      ['Aluminum chloride', 'Fumaric acid'],
        tempC:         130,
        timeH:         0.25,
        solvent:       'DMF',
        modulator:     null,
        yieldPct:      68,
        crystallinity: 'Medium',
    },
    {
        id:            'RXN-012',
        reactionType:  'Hydrothermal',
        reagents:      ['Copper(II) acetate', 'Oxalic acid', 'NaOH'],
        tempC:         200,
        timeH:         48,
        solvent:       'Water',
        modulator:     null,
        yieldPct:      53,
        crystallinity: 'High',
    },
    {
        id:            'RXN-013',
        reactionType:  'Solvothermal',
        reagents:      ['Chromium(III) nitrate', 'Terephthalic acid', 'HF'],
        tempC:         220,
        timeH:         72,
        solvent:       'Water/DMF',
        modulator:     'HF',
        yieldPct:      70,
        crystallinity: 'High',
    },
    {
        id:            'RXN-014',
        reactionType:  'Reflux',
        reagents:      ['Iron(III) chloride', 'DABCO', 'Triethylamine'],
        tempC:         80,
        timeH:         6,
        solvent:       'Acetonitrile',
        modulator:     null,
        yieldPct:      35,
        crystallinity: 'Low',
    },
    {
        id:            'RXN-015',
        reactionType:  'Mechanochemical',
        reagents:      ['Copper(II) acetate', '2-Methylimidazole'],
        tempC:         25,
        timeH:         1,
        solvent:       'None',
        modulator:     null,
        yieldPct:      82,
        crystallinity: 'Low',
    },
    {
        id:            'RXN-016',
        reactionType:  'Solvothermal',
        reagents:      ['Indium(III) chloride', 'Trimesic acid', 'Triethylamine'],
        tempC:         140,
        timeH:         36,
        solvent:       'DMF',
        modulator:     null,
        yieldPct:      61,
        crystallinity: 'Medium',
    },
    {
        id:            'RXN-017',
        reactionType:  'Hydrothermal',
        reagents:      ['Zinc nitrate', 'Fumaric acid', 'DABCO'],
        tempC:         160,
        timeH:         72,
        solvent:       'Water',
        modulator:     null,
        yieldPct:      74,
        crystallinity: 'High',
    },
    {
        id:            'RXN-018',
        reactionType:  'Solvothermal',
        reagents:      ['Nickel(II) nitrate', 'Terephthalic acid', 'Triethylamine'],
        tempC:         130,
        timeH:         48,
        solvent:       'DEF',
        modulator:     'Acetic acid',
        yieldPct:      67,
        crystallinity: 'Medium',
    },
    {
        id:            'RXN-019',
        reactionType:  'Microwave-Assisted',
        reagents:      ['Zinc nitrate', 'Trimesic acid'],
        tempC:         120,
        timeH:         0.5,
        solvent:       'DMF',
        modulator:     null,
        yieldPct:      58,
        crystallinity: 'Medium',
    },
    {
        id:            'RXN-020',
        reactionType:  'Reflux',
        reagents:      ['Cobalt(II) chloride', 'DABCO', 'Terephthalic acid'],
        tempC:         78,
        timeH:         8,
        solvent:       'Ethanol',
        modulator:     null,
        yieldPct:      44,
        crystallinity: 'Low',
    },
    {
        id:            'RXN-021',
        reactionType:  'Solvothermal',
        reagents:      ['Zinc nitrate', 'DABCO', 'Terephthalic acid'],
        tempC:         100,
        timeH:         48,
        solvent:       'DMF',
        modulator:     null,
        yieldPct:      71,
        crystallinity: 'High',
    },
    {
        id:            'RXN-022',
        reactionType:  'Hydrothermal',
        reagents:      ['Copper(II) acetate', 'Fumaric acid', 'NaOH'],
        tempC:         180,
        timeH:         60,
        solvent:       'Water',
        modulator:     null,
        yieldPct:      59,
        crystallinity: 'Medium',
    },
    {
        id:            'RXN-023',
        reactionType:  'Microwave-Assisted',
        reagents:      ['Zinc nitrate', 'Terephthalic acid', 'Triethylamine'],
        tempC:         130,
        timeH:         0.75,
        solvent:       'DMF',
        modulator:     'Acetic acid',
        yieldPct:      76,
        crystallinity: 'Medium',
    },
    {
        id:            'RXN-024',
        reactionType:  'Solvothermal',
        reagents:      ['Cobalt(II) nitrate', 'DABCO', 'Terephthalic acid'],
        tempC:         140,
        timeH:         72,
        solvent:       'DEF',
        modulator:     null,
        yieldPct:      63,
        crystallinity: 'High',
    },
    {
        id:            'RXN-025',
        reactionType:  'Mechanochemical',
        reagents:      ['Nickel(II) chloride', '2-Methylimidazole'],
        tempC:         25,
        timeH:         1.5,
        solvent:       'None',
        modulator:     null,
        yieldPct:      78,
        crystallinity: 'Low',
    },
    {
        id:            'RXN-026',
        reactionType:  'Hydrothermal',
        reagents:      ['Zirconium chloride', 'Fumaric acid', 'Acetic acid'],
        tempC:         220,
        timeH:         96,
        solvent:       'Water/DMF',
        modulator:     'Acetic acid',
        yieldPct:      82,
        crystallinity: 'High',
    },
    {
        id:            'RXN-027',
        reactionType:  'Reflux',
        reagents:      ['Iron(III) chloride', 'Oxalic acid', 'Triethylamine'],
        tempC:         90,
        timeH:         10,
        solvent:       'Ethanol',
        modulator:     null,
        yieldPct:      38,
        crystallinity: 'Low',
    },
    {
        id:            'RXN-028',
        reactionType:  'Solvothermal',
        reagents:      ['Manganese(II) chloride', 'Trimesic acid'],
        tempC:         160,
        timeH:         48,
        solvent:       'DMF',
        modulator:     null,
        yieldPct:      56,
        crystallinity: 'Medium',
    },
    {
        id:            'RXN-029',
        reactionType:  'Microwave-Assisted',
        reagents:      ['Copper(II) nitrate', 'Terephthalic acid'],
        tempC:         125,
        timeH:         0.33,
        solvent:       'DMF',
        modulator:     'HCl',
        yieldPct:      64,
        crystallinity: 'Medium',
    },
    {
        id:            'RXN-030',
        reactionType:  'Solvothermal',
        reagents:      ['Lanthanum(III) nitrate', 'Trimesic acid', 'Triethylamine'],
        tempC:         150,
        timeH:         72,
        solvent:       'DMF',
        modulator:     null,
        yieldPct:      45,
        crystallinity: 'Medium',
    },
    {
        id:            'RXN-031',
        reactionType:  'Hydrothermal',
        reagents:      ['Zinc nitrate', 'Oxalic acid', 'NaOH'],
        tempC:         200,
        timeH:         48,
        solvent:       'Water',
        modulator:     null,
        yieldPct:      66,
        crystallinity: 'High',
    },
    {
        id:            'RXN-032',
        reactionType:  'Solvothermal',
        reagents:      ['Copper(II) acetate', 'DABCO', 'Terephthalic acid'],
        tempC:         110,
        timeH:         36,
        solvent:       'DMF',
        modulator:     'Acetic acid',
        yieldPct:      80,
        crystallinity: 'High',
    },
    {
        id:            'RXN-033',
        reactionType:  'Mechanochemical',
        reagents:      ['Cobalt(II) chloride', '2-Methylimidazole'],
        tempC:         25,
        timeH:         2,
        solvent:       'None',
        modulator:     null,
        yieldPct:      75,
        crystallinity: 'Low',
    },
    {
        id:            'RXN-034',
        reactionType:  'Reflux',
        reagents:      ['Nickel(II) nitrate', 'DABCO', 'Triethylamine'],
        tempC:         85,
        timeH:         14,
        solvent:       'Acetonitrile',
        modulator:     null,
        yieldPct:      41,
        crystallinity: 'Low',
    },
    {
        id:            'RXN-035',
        reactionType:  'Solvothermal',
        reagents:      ['Yttrium(III) nitrate', 'Terephthalic acid', 'Acetic acid'],
        tempC:         130,
        timeH:         48,
        solvent:       'DMF',
        modulator:     'Acetic acid',
        yieldPct:      69,
        crystallinity: 'Medium',
    },
    {
        id:            'RXN-036',
        reactionType:  'Hydrothermal',
        reagents:      ['Aluminum sulfate', 'Fumaric acid', 'NaOH'],
        tempC:         200,
        timeH:         72,
        solvent:       'Water',
        modulator:     null,
        yieldPct:      51,
        crystallinity: 'High',
    },
    {
        id:            'RXN-037',
        reactionType:  'Solvothermal',
        reagents:      ['Iron(III) chloride', 'Trimesic acid', 'Acetic acid'],
        tempC:         150,
        timeH:         48,
        solvent:       'DMF/EtOH',
        modulator:     'Acetic acid',
        yieldPct:      73,
        crystallinity: 'High',
    },
    {
        id:            'RXN-038',
        reactionType:  'Microwave-Assisted',
        reagents:      ['Nickel(II) nitrate', 'DABCO', 'Terephthalic acid'],
        tempC:         145,
        timeH:         0.5,
        solvent:       'DMF',
        modulator:     null,
        yieldPct:      62,
        crystallinity: 'Medium',
    },
    {
        id:            'RXN-039',
        reactionType:  'Solvothermal',
        reagents:      ['Manganese(II) chloride', 'Fumaric acid', 'Triethylamine'],
        tempC:         120,
        timeH:         36,
        solvent:       'DEF',
        modulator:     null,
        yieldPct:      57,
        crystallinity: 'Medium',
    },
    {
        id:            'RXN-040',
        reactionType:  'Hydrothermal',
        reagents:      ['Cobalt(II) nitrate', 'Oxalic acid', 'NaOH'],
        tempC:         190,
        timeH:         60,
        solvent:       'Water',
        modulator:     null,
        yieldPct:      49,
        crystallinity: 'High',
    },
];

export const allReagents = [...new Set(reactions.flatMap(r => r.reagents))].sort();
